ParkyWeb/Models/ErrorViewModel.cs
using System;

namespace ParkyWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ParkyWeb/Models/NationalPark.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ParkyWeb.Models
{
    public class NationalPark
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string State { get; set; }

        public DateTime Created { get; set; }

        public byte[] Picture { get; set; }

        public DateTime Established { get; set; }
    }
}

ParkyWeb/Models/Trail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ParkyWeb.Models
{
    public class Trail
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public double Distance { get; set; }
        [Required]
        public double Elevation { get; set; }
        public enum DifficultyType { Easy, Moderate, Difficult, Expert }
        public DifficultyType Difficulty { get; set; }
        [Required]
        public int NationalParkId { get; set; }

        public NationalPark NationalPark { get; set; }
    }
}

ParkyWeb/Models/ViewModel/TrailsVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ParkyWeb.Models.ViewModel
{
    public class TrailsVM
    {
        public IEnumerable<SelectListItem> NationalParkList { get; set; }
        public Trail Trail { get; set; }
    }
}

ParkyWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ParkyWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ParkyWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ParkyWeb/Controllers/NationalParksController.cs
using Microsoft.AspNetCore.Mvc;
using ParkyWeb.Models;
using ParkyWeb.Repository.IRepository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ParkyWeb.Controllers
{
    public class NationalParksController : Controller
    {
        private readonly INationalParkRepository _npRepo;
        public NationalParksController(INationalParkRepository nprepo)
        {
            _npRepo = nprepo;
        }
        public IActionResult Index()
        {
            return View(new NationalPark() { });
        }

        public async Task<IActionResult> GetAllNationalPark()
        {
            return Json(new { data = await _npRepo.GetAllAsync(SD.NationalParkApiPath) });
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            NationalPark obj = new NationalPark();
            if (id == null)
            {
                return View(obj);
            }

            obj = await _npRepo.GetAsync(SD.NationalParkApiPath, id.GetValueOrDefault());

            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(NationalPark obj)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    obj.Picture = p1;
                }
                else
                {
                    var objFromDb = await _npRepo.GetAsync(SD.NationalParkApiPath, obj.Id);
                    obj.Picture = objFromDb.Picture;
                }
                if (obj.Id == 0)
                {
                    await _npRepo.CreateAsync(SD.NationalParkApiPath, obj);
                }
                else
                {
                    await _npRepo.UpdateAsync(SD.NationalParkApiPath + obj.Id, obj);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(obj);
            }

        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _npRepo.DeleteAsync(SD.NationalParkApiPath, id);

            if (status) {
                return Json(new { success = true, message = "Delete Successfull."});
            }

            return Json(new { success = false, message = "Delete Not Successfull." });
        }
    }
}

ParkyWeb/Controllers/TrailsController.cs
using Microsoft.AspNetCore.Mvc;
using ParkyWeb.Models;
using ParkyWeb.Models.ViewModel;
using ParkyWeb.Repository.IRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;

namespace ParkyWeb.Controllers
{
    public class TrailsController : Controller
    {
        private readonly INationalParkRepository _npRepo;
        private readonly ITrailRepository _trailRepo;
        public TrailsController(ITrailRepository trailRepo, INationalParkRepository npRepo)
        {
            _trailRepo = trailRepo;
            _npRepo = npRepo;
        }
        public IActionResult Index()
        {
            return View(new Trail() { });
        }

        public async Task<IActionResult> GetAllTrails()
        {
            return Json(new { data = await _trailRepo.GetAllAsync(SD.TrailApiPath) });
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            IEnumerable<NationalPark> npList = await _npRepo.GetAllAsync(SD.NationalParkApiPath);

            TrailsVM objVM = new TrailsVM()
            {
                NationalParkList = npList.Select(i=> new SelectListItem { 
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };

            if (id == null)
            {
                return View(objVM);
            }

            objVM.Trail = await _trailRepo.GetAsync(SD.TrailApiPath, id.GetValueOrDefault());

            if (objVM.Trail == null)
            {
                return NotFound();
            }
            return View(objVM.Trail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(TrailsVM obj)
        {
            if (ModelState.IsValid)
            {
                
                if (obj.Trail.Id == 0)
                {
                    await _trailRepo.CreateAsync(SD.TrailApiPath, obj.Trail);
                }
                else
                {
                    await _trailRepo.UpdateAsync(SD.TrailApiPath + obj.Trail.Id, obj.Trail);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(obj);
            }

        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _trailRepo.DeleteAsync(SD.TrailApiPath, id);

            if (status)
            {
                return Json(new { success = true, message = "Delete Successfull." });
            }

            return Json(new { success = false, message = "Delete Not Successfull." });
        }
    }
}

ParkyWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome API</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ParkyWeb/Views/NationalParks/Index.cshtml
<div class="p-4" style="border-radius:20px;">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">National Park List</h2>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary text-white" asp-action="Upsert"><i class="fas fa-plus"></i> &nbsp; Create New National Park</a>
        </div>
    </div>
    <br />
    <br />
    <div style="background-color:#cde8e2" class="p-3 rounded">
        <table id="tblData" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr class="table-danger">
                    <th>Name</th>
                    <th>State</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{ 
<script src="~/js/nationalPark.js"></script>

}

ParkyWeb/Views/NationalParks/Upsert.cshtml
@model ParkyWeb.Models.NationalPark
@{ 
    var title = "Create National park";
}
<form method="post" asp-action="Upsert" enctype="multipart/form-data">

    <div class="row px-2 mx-2 backgroundWhite border">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (Model.Id != 0) {
            <input type="hidden" asp-for="Id" />
            title = "Edit National Park";
        }

        <div class="col-12 p-3">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="State"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Picture"></label>
                </div>
                <div class="col-8">
                    <input type="file" asp-for="Picture" id="projectImage" name="files" multiple class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Established"></label>
                </div>
                <div class="col-8">
                    @{
                        var dateEst = "";
                        if (Model.Id != 0)
                        {
                            dateEst = Model.Established.ToShortDateString();
                        }
                    }
                    <input type="text" asp-for="Established" id="datepicker" value="@dateEst" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4 offset-4">
                    <button type="submit" class="btn btn-primary form-control">
                        @(Model.Id!=0?"Update":"Create")
                    </button>
                </div>
                <div class="col-4">
                    <a class="btn btn-success form-control" asp-action="Index">Back to List</a>
                </div>
            </div>

        </div>
        <div class="col-4 text-right" style="width:250px;">
            @if (Model.Picture != null)
            {
                var base64 = Convert.ToBase64String(Model.Picture);
                var imgstr = string.Format("data:image/jpg;base64,{0}", base64);
                <img src="@imgstr" width="100%" />
            }
        </div>
    </div>

</form>


@section Scripts{
    <script>
        $(function () {
            $("#datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1900:2021"
            });
        });
    </script>

}

ParkyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParkyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ParkyWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NationalParks" asp-action="Index">National Park</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trails" asp-action="Index">Trail</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ParkyWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ParkyWeb/Views/Trails/Index.cshtml
<div class="p-4" style="border-radius:20px;">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Trail List</h2>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary text-white" asp-action="Upsert"><i class="fas fa-plus"></i> &nbsp; Create New Trail</a>
        </div>
    </div>
    <br />
    <br />
    <div class="p-3 rounded">
        <table id="tblData" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr class="table-danger">
                    <th>National Park</th>
                    <th>Trail Name</th>
                    <th>Distance</th>
                    <th>Elevation</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/trail.js"></script>

}

ParkyWeb/Views/Trails/Upsert.cshtml
@model ParkyWeb.Models.ViewModel.TrailsVM
@{
    var title = "Create Trail";
}
<form method="post" asp-action="Upsert">

    <div class="row px-2 mx-2 backgroundWhite">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (Model.Trail.Id != 0)
        {
            <input type="hidden" asp-for="Trail.Id" />
            title = "Edit Trail";
        }

        <div class="col-12 p-3">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    National Park
                </div>
                <div class="col-8">
                    @Html.DropDownListFor(m=>m.Trail.NationalParkId, Model.NationalParkList, "-Plese select Park-"
                    , new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Trail.Name"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Trail.Name" class="form-control" />
                    <span asp-validation-for="Trail.Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Trail.Difficulty"></label>
                </div>
                <div class="col-8">
                    <select asp-for="Trail.Difficulty" asp-items="Html.GetEnumSelectList<Trail.DifficultyType>()" class="form-control"></select>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Trail.Difficulty"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Trail.Difficulty" class="form-control" />
                    <span asp-validation-for="Trail.Difficulty" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Trail.Elevation"></label>
                </div>
                <div class="col-8">
                    <input type="text" asp-for="Trail.Elevation" class="form-control" />
                    <span asp-validation-for="Trail.Elevation" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-4 offset-4">
                    <button type="submit" class="btn btn-primary form-control">
                        @(Model.Trail.Id!=0?"Update":"Create")
                    </button>
                </div>
                <div class="col-4">
                    <a class="btn btn-success form-control" asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>
    </div>

</form>